### ISSUE TITLE
[June 2019] Code Review

### ISSUE THREAD

**Issue by dserban** [Morphl-AI/MorphL-Model-Ecommerce-Predict-Next-Action#1]
● Here: https://github.com/Morphl-AI/MorphL-Model-Ecommerce-Predict-Next-Action/blob/feature/batch-inference/pre_processing/basic_processing/ga_epna_basic_preprocessor.py#L435-L445

> [Aesthetics] The unnecessary parentheses are an eyesore :)

● Here: https://github.com/Morphl-AI/MorphL-Model-Ecommerce-Predict-Next-Action/blob/feature/batch-inference/cassandra_schema/ga_epna_cassandra_schema.cql#L131

> the set should be frozen:
```
  shopping_stage frozen<set<text>>,
```

● Here: https://github.com/Morphl-AI/MorphL-Model-Ecommerce-Predict-Next-Action/blob/feature/batch-inference/cassandra_schema/ga_epna_cassandra_schema.cql#L176

> the `INSERT` statement is incomplete.

**Comment by abarbulescu** [comment]
https://github.com/Morphl-AI/MorphL-Model-Ecommerce-Predict-Next-Action/commit/b2f3559bb3e112a51fd3872a4d94529e02b96b6a, https://github.com/Morphl-AI/MorphL-Model-Ecommerce-Predict-Next-Action/commit/2823482f6e09a6e39c8c7cc75eabaf0cba3d5f3b ,https://github.com/Morphl-AI/MorphL-Model-Ecommerce-Predict-Next-Action/commit/cfc74e61b635e0ff4d3189cf629fcb649393b18f
